### PR TITLE
Add the zh-tw Translations for v1.0.0

### PR DESCRIPTION
**Pull request by AaronChern**
1. "apply" is "申請" for the most situation, but the zh-tw translation should be "儲存變更" here.
2. add some Pan-Asia shipnames.

### CODE REVIEW

**Comment by anmonite** [comment]
AaronChern, thank you for this zh-tw translation.

I  appreciate your rapid cooperation.

**Comment by anmonite** [comment]
I will release v1.0.1 soon with including changes of this commit.

**Comment by anmonite** [comment]
Hi AaronChern,

I would like to ask you an translation. 
My clan member would provide a figure for explanation of measurement of combat power/WTR/PR ranking as follows.

for en-us:
en

for zh-tw: 
zh_tw

Could you translate English strings part to your language?

Regards.

**Comment by AaronChern** [comment]
Hi @anmonite ,
Here are the translations:

Super Unicum 超級傑出
Unicum 傑出
Great  優秀
Very Good 非常不錯
Good 不錯
Average 平均
Below Average 低於平均
Bad 不好
Very Bad 非常不好 

===

By the way, I have some suggestions about the layout.

1. Sync the column width of the "K/D" of the "Ship score" to the "Total score" in zh-tw translation mode. Since I changed the translation of "K/D" of the "Ship score" last time. Instead of the translation, I used “K/D” directly. Both "Ship score" and "Total score" use “K/D” now.

2. Highlight the "Number of battle" under 30. Little battle counts doesn’t have any meaning of statistics. I hope we can remind users of this.

**Comment by anmonite** [comment]
Many thanks for your kindly cooperation!

I will implement these figures as a description picture when user point <th> column of CP/WTR/PR with mouse over in the next release.

About suggestions you sent,
1. I found the width difference between "K/D" column of both ship and player. So I will fix it with both width equal to 55px.

2. About highlighted row, I think it should not judge highlight or not by only battle counts of the ship. Because there is a case which strong player buy a new ship recently. I will keep considering to find a best way to resolve this issue.

thanks.

**Comment by AaronChern** [comment]
About the suggestion 2, I didn't mean highlight the whole "row". 
I meant only highlight the "cell" of "Number of battle" which is under 30 to remind the users of this.

**Comment by AaronChern** [comment]
Hi @anmonite ,

I add three zh-tw translations for version 0.6.12.

1. [Clan Battles]
mode.CvC_Domination   公會戰鬥:制海權

2.  [Halloween Scenarios Pt. I]  
Saving Transylvania    拯救外西凡尼亞

3.  [Halloween Scenarios Pt. II]
A Sunray Through the Dark  黑暗中的光芒

**Comment by anmonite** [comment]
Thanks to provide quickly information.

I will implement that translated strings on release ver. 1.0.2 earlier.

Clan war
mode:
"CvC_Domination": "公會戰鬥: 制海權"

Halloween event
map:
"50_VanHellsing": "拯救外西凡尼亞"
"e02_Halloween_2017": "黑暗中的光芒"

mode:
"PVEVanHellsingRight": "萬聖節活動： 第一部份"
"Halloween_2017": "萬聖節活動： 第二部份"

Is it OK?

**Comment by AaronChern** [comment]
Yes, it is OK.

**Pull request merged**
