### PR TITLE
Add zh-tw translation for Musashi and modify typo

### PR DESCRIPTION
**Pull request by AaronChern**

### CODE REVIEW

**Comment by AaronChern** [comment]
Hi @anmonite ,
I have modified "武蔵" to 武藏 in shipname.json for Taiwanese usage, and remove redundant typo "1" in lang_ru.json.  
Please merge this commit. Thank you. 
If you have any questions, please let me know.

**Comment by anmonite** [comment]
Hi AaronChern,

Thank you for your update and fix with keen eyes.

By the way, I received a pull request for zh-tw shipname translation #9 by alex .
I wonder that that translating whole shipname in zh-tw  is suitable for Taiwan users or not.

Please feel free to replay comments about this change.

**Comment by AaronChern** [comment]
Hi @anmonite ,
I agree with you opinion too.
"In Japanese, many people prefer to translate ship name only Japanese and Pan Asian ships (those ship name have Chinese characters in basis). So I have been leaving other ship name as is."

This patch #9  is not necessary. 
Most of them are "pronunciation translation", it may differ by translators.

**Comment by anmonite** [comment]
Thanks for your opinion and agreement!

I decide to reject #9 . That translation should keep being as a local change.

**Pull request merged**
