### PR TITLE
added dynamic hostname to make it usable from tablets

### PR DESCRIPTION
**Pull request by MightyWizard83**
added dynamic hostname to make it usable from tablets

### CODE REVIEW

**Comment by anmonite** [comment]
Hi MightyWizard83.

Please describe the backbone of this pull-request in detail.
Because I don't expect to use wows-stats-plus on tablets (Windows tablets?) :)

**Comment by MightyWizard83** [comment]
Hi Anmonite,
currently wows-stats-plus forces the user to ALT+TAB or use a secondary display to read the stats from a the browser.
This makes wows-stats-plus difficoult to use for players with a single monitor running in full-screen.

This simple pull request enable the user to navigate to wows-stats-plus webpage from a tablet connected to the same wireless network than the pc that runs wows-stats-plus by typing the host IP and port.

Of course this is a "feature for experts" since you must know what your IP is, but I think it's an useful feature that will enable more players to be able to use this useful application.

**Comment by MightyWizard83** [comment]
Example: my PC's IP is 192.168.0.1
when I launch wows-stats-plus I can access it from my pc by typing http://localhost:8080 and it works fine.

If I want to access it from my tablet I have to navigate to http://192.168.0.1:8080
I will be able to load the first  page, but the ajax calls will not work from the tablet  because they will try co contact localhost.

by changing "localhost:8080" with window.location.hostname+':'+window.location.port the ajax calls will work both on the tablet and the pc (no regression, since window.location functions are a widely supported standard)

**Comment by anmonite** [comment]
Thanks for your detailed explanation. I understand your request.

After my implementation of this modification and testing it, I will let you know the result.
Please wait for several days.

cheers,

**Comment by anmonite** [comment]
After my investigation of js sources, only install/js/app.js has static hostname. The static/js/app.js was already resolved this issue on latest version.
So that NOW you can use wows-stats-plus from any external device's browser.

This issue is come from original wows-stats part and I have never done enough about source code refactoring with installer modules yet.
So I will update  install/js/app.js in the next release.

Thanks,

**Comment by anmonite** [comment]
To change simply, I think remove all part of "'http://'+window.location.hostname+':'+window.location.port+"  is the best solution.
To use local API, calling short URL that starts "/" like as "/api/env" is enough to use simply.

Please modify your code if you feel that there is no problem to change as above.

**Comment by MightyWizard83** [comment]
@anmonite I like your idea.
I tested it starting from a clean installation and worked flawlessly both in PC's browser and external tablet.
No regression during a fresh install process nor in the normal app usage.

**Comment by anmonite** [comment]
Many thanks for your cooperation!

This PR made me realize a possibility that wows-stats-plus can provide on-time stats information to live playing (twitch) listeners via internet.

After modification DMZ setting of my home router, I tried to access wows-stats-plus via internet. And I made it with success :)  Of course, I have to check my js codes from vulnerability point of view if I will announce this use to users.

**Comment by anmonite** [comment]
By the way, could you introduce my wows-stats-plus to your clan members, and more to say post introduction message to the board of WG EU forum?

The base introduction message in English was posted on "[English Speaking Community board of WG Asia](https://forum.worldofwarships.asia/topic/24638-mod-wows-stats-plus-gives-you-detailed-matching-players-score/)".

And then, could you write "static/js/laguage/lang_it.json" translation file for Italian users if there are some Italian users to be expected to use may app?

**Pull request merged**
