### PR TITLE
The Chinese(zh-tw) Translation

### PR DESCRIPTION
**Pull request by AaronChern**
Hi anmonite,

This is the Chinese(zh-tw) translation reviewed by the World of Warships community in Taiwan.

Please merge it after your review. Thank you.

### CODE REVIEW

**Comment by anmonite** [comment]
Great!  Many thanks for your cooperation.

I did expect that you might cooperate with me about zh-tw translation.

Before merge them into my repository , I found unexpected "," at the end of line 172 (Lo Yang) of "shipname.json". Could you please remove it and send request again?

**Comment by anmonite** [comment]
And then, is it suitable that the label of "撃沈數÷死亡數" shrink to "撃沈/死亡" ?
It seems width of that cell is wider than other cells.

**Comment by AaronChern** [comment]
I see. I will modify them.
For the width of the cell, should "tier": "船階"  change to  "tier": "T"

**Comment by anmonite** [comment]
It seems that you forgot to commit about change from "船階" to "T". Check please.

**Comment by anmonite** [comment]
AaronChern, thanks for your kindly responses.
I just now merged your request into my repository.
I will make release version as v_0.5.7. Wait my announce please.

**Comment by AaronChern** [comment]
Thank you, anmonite.
It is my honor to cooperate with you.

**Comment by anmonite** [comment]
FYI, if you are interested in a solution to switch active window between wows game client and xvm application mode browser by hitting CTRL(or ALT) key twice, please look at my blog post as follows (can translate by Google plugin).

https://moon-light-oasis.net/game/20170822123544.html

**Comment by AaronChern** [comment]
Hi anmonite,
I saw you "Merge branch 'release/0.5.7'    Latest commit 1a50d87  2 days ago"
Can I use this version for the Chinese Translation?

**Comment by anmonite** [comment]
Hi, AaronChern.

Yes, you can use 0.5.7 as implemented zh-tw translation version. But I have never announced on WG Asia forum and also my blog about this update. Because it seems this is a small change for many users.

I'm sorry that I did't announce to you about that.

I'm now in progress for update to 0.6.0 with supporting new UI of display column setting feature.
[Screenshot from Gyazo](https://gyazo.com/573d596befe60381e75e7aa0723cd6dc)

Thanks.

**Comment by AaronChern** [comment]
Hi anmonite,
Thank you.
I am looking forward to 0.6.0.

**Pull request merged**
